openapi: 3.0.0

info:
    title: MN Konveksi API
    version: '1.0.0'
    description: API resmi MN Konveksi

servers:
    - url: https://be-mn-konveksi.vercel.app
      description: Production
    - url: http://localhost:5000
      description: Local Development

tags:
    $ref: ./tags.yaml

components:
    $ref: ./security.yaml

paths:
    # =========================
    # AUTH
    # =========================
    /api/auth/register:
        $ref: ./paths/auth.yaml#/api/auth/register
    /api/auth/login:
        $ref: ./paths/auth.yaml#/api/auth/login
    /api/auth/me:
        $ref: ./paths/auth.yaml#/api/auth/me
    /api/auth/logout:
        $ref: ./paths/auth.yaml#/api/auth/logout

    # =========================
    # PRODUK
    # =========================
    /api/produk:
        $ref: ./paths/produk.yaml#/api/produk
    /api/produk/{id}:
        $ref: ./paths/produk.yaml#/api/produk/{id}

    # =========================
    # PESANAN
    # =========================
    /api/pesanan:
        $ref: ./paths/pesanan.yaml#/api/pesanan
    /api/pesanan/me/summary:
        $ref: ./paths/pesanan.yaml#/api/pesanan/me/summary
    /api/pesanan/{id}:
        $ref: ./paths/pesanan.yaml#/api/pesanan/{id}
    /api/pesanan/{id}/status:
        $ref: ./paths/pesanan.yaml#/api/pesanan/{id}/status
    /api/pesanan/admin/summary:
        $ref: ./paths/pesanan.yaml#/api/pesanan/admin/summary

    # TRANSAKSI
    /api/transaksi/create:
        $ref: ./paths/transaksi.yaml#/api/transaksi/create
    /api/transaksi/webhook:
        $ref: ./paths/transaksi.yaml#/api/transaksi/webhook
