securitySchemes:
    bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT

schemas:
    User:
        $ref: ./schemas/user.yaml#/User
    UserRegister:
        $ref: ./schemas/user.yaml#/UserRegister
    UserLogin:
        $ref: ./schemas/user.yaml#/UserLogin
    Produk:
        $ref: ./schemas/produk.yaml#/Produk
    Pesanan:
        $ref: ./schemas/pesanan.yaml#/Pesanan
    PesananCreate:
        $ref: ./schemas/pesanan.yaml#/PesananCreate
    PesananSummaryUser:
        $ref: ./schemas/pesanan.yaml#/PesananSummaryUser
    PesananSummaryAdmin:
        $ref: ./schemas/pesanan.yaml#/PesananSummaryAdmin

    Transaksi:
        $ref: ./schemas/transaksi.yaml#/Transaksi
    TransaksiCreate:
        $ref: ./schemas/transaksi.yaml#/TransaksiCreate
    TransaksiSnapResponse:
        $ref: ./schemas/transaksi.yaml#/TransaksiSnapResponse
    MidtransWebhook:
        $ref: ./schemas/transaksi.yaml#/MidtransWebhook
