openapi: 3.0.0

info:
    title: MN Konveksi API
    version: '1.0.0'
    description: API resmi MN Konveksi

servers:
    - url: https://be-mn-konveksi.vercel.app
    - local url: http://localhost:5000

tags:
    $ref: ./tags.yaml

components:
    $ref: ./security.yaml

paths:
    $ref: ./paths/auth.yaml
